### ISSUE TITLE
Ansible unreachable error in slurm playbook. 

### ISSUE THREAD

**Issue by mikeoconnor0308** [ACRC/cluster-in-the-cloud#2]
I'm attempting to set up a small cluster-in-the-cloud on my OCI tenancy. The only changes I've made to the original are to use a couple of VM.GPU2.1 nodes as the compute nodes. It all appeared to be going well, until the `finish` script failed at: 

```
rc = subprocess.call(['ansible-playbook', '--inventory=/home/opc/hosts', '--extra-vars=@/home/opc/users.yml', 'finalise.yml'], cwd='/home/opc/slurm-ansible-playbook')
```

with the following output: 

```
[opc@mgmt ~]$ ./finish

PLAY [finalise] *********************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [mgmt]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"mgmt\". Make sure this host can be reached over ssh", "unreachable": true}
fatal: [compute002]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"compute002\". Make sure this host can be reached over ssh", "unreachable": true}
fatal: [compute001]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to remote host \"compute001\". Make sure this host can be reached over ssh", "unreachable": true}
        to retry, use: --limit @/home/opc/slurm-ansible-playbook/finalise.retry

PLAY RECAP **************************************************************************************************************************************************************************************************************************************************************************************************************
compute001                 : ok=0    changed=0    unreachable=1    failed=0   
compute002                 : ok=0    changed=0    unreachable=1    failed=0   
mgmt                       : ok=0    changed=0    unreachable=1    failed=0   


#############################################
Error: Ansible run did not complete correctly
#############################################
```

I'm able to ssh into the instances, so I'm not sure what's going wrong here? Any help would be much appreciated!

**Comment by milliams** [comment]
In order for the OPC user to be able to SSH into the compute nodes, it needs to access your private keys. The way it does this is using SSH Agent forwarding from your local machine. This avoids needing to put your private keys on the server and instead the request is passed through the pipe.

To enable SSH agent forwarding you need:
1. to be running ssh-agent on your local machine [[1]](https://help.github.com/en/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent#adding-your-ssh-key-to-the-ssh-agent) or [[2]](https://www.ssh.com/ssh/agent)
2. to connect to the mgmt server using the `-A` flag for SSH

You can test whether this is working using the [step in the docs](https://cluster-in-the-cloud.readthedocs.io/en/latest/ansible.html#final-configuration-step):

```bash
ssh-add -L
```

and checking that it prints the key you're using.

**Comment by milliams** [comment]
Also, since in the meantime Slurm will have turned off those compute nodes to save you money, you'll need to start them again in order to run the finish script.

You can either `terraform destroy` and `apply` your cluster if it's currently empty and doesn't contain any data you want to keep. Or, you can submit [a job like this](https://cluster-in-the-cloud.readthedocs.io/en/latest/running.html#slurm-jobs) as root, setting `#SBATCH --nodes=1` to `#SBATCH --nodes=2`

**Comment by mikeoconnor0308** [comment]
Ah thanks a lot, I got ahead of myself and skipped that step in the docs.
